version: '3.5'
services:

# must still be filled with content


  olahds_backend:
    build:                         # on mac osx based host
      context: .
      dockerfile: Dockerfile
    container_name: olahds_backend
    links:
      - olahds_mongo
      - olahds_web_notifier
    depends_on:
      olahds_mongo:
        condition: service_started
      olahds_web_notifier:
        condition: service_started
      olahds_search:
        condition: service_healthy
    env_file: .env
    networks:
      olahd:
        aliases:
          - backend

  olahds_web_notifier:
    image: docker.gitlab.gwdg.de/subugoe/metsimporter/web:latest
    #build:                         # on mac osx based host
    #  context: web
    #  dockerfile: Dockerfile
    command: /usr/local/bin/web -d /etc/env/
    container_name: olahds_web_notifier
    ports:
      - "1323:1323"
    links:
      - olahds_redis
      - olahds_indexer
    depends_on:
      - olahds_redis
      - olahds_indexer
  
  olahds_indexer:
    image: docker.gitlab.gwdg.de/subugoe/metsimporter/indexer:latest
    #build:                         # on mac osx based host
    #  context: indexer
    #  dockerfile: Dockerfile
    command: /usr/local/bin/indexer -d /etc/env/
    container_name: olahds_indexer
    links:
      - olahds_redis
      - olahds_search
    depends_on:
      olahds_redis:
        condition: service_started
      olahds_search:
        condition: service_healthy
    networks:
      olahd:


networks:
  olahd:
    name: olahd
    driver: bridge                       
    #driver_opts:                         
    #  com.docker.network.driver.mtu: 1450
  
